#!/bin/bash

if [ -d ${OPENSHIFT_DATA_DIR}/conf ] ; then
    cp ${OPENSHIFT_REPO_DIR}/conf/*.conf ${OPENSHIFT_DATA_DIR}/conf
else
    mkdir -p ${OPENSHIFT_DATA_DIR}/conf
    cp ${OPENSHIFT_REPO_DIR}/conf/*.conf ${OPENSHIFT_DATA_DIR}/conf
fi


sed -i -e "s@OPENSHIFT_INTERNAL_IP@$OPENSHIFT_PYTHON_IP@g" -e "s@OPENSHIFT_HOMEDIR@$OPENSHIFT_HOMEDIR@g" -e "s@OPENSHIFT_DATA_DIR@$OPENSHIFT_DATA_DIR@g" -e "s@OPENSHIFT_LOG_DIR@$OPENSHIFT_PYTHON_LOG_DIR@g" -e "s@CONFIG_DIR@${OPENSHIFT_DATA_DIR}/conf@g" ${OPENSHIFT_DATA_DIR}/conf/*.conf

httpd -f ${OPENSHIFT_DATA_DIR}/conf/httpd.conf -k start

exit 0
